---
- name: Installing required packages
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python-mysqldb
    - mysql-server
    - mysql-client

- name: Making sure MySQL is running
  service:
    name: mysql
    state: started
