---
  - name: Configure AFP shares
    template:
      src: "afp.conf.j2"
      dest: "/usr/local/etc/afp.conf"
    when: nginx_sites | length > 0
    notify:
      - Reload avahi
      - Start Netatalk
