---
  - name: Install NTP package
    apt:
      pkg: ntp
      state: present
      update_cache: yes

  - name: Configure NTP
    template:
      src: ntp.conf.j2
      dest: /etc/ntp.conf
      mode: 0644
    notify: Restart NTP

  - name: Set timezone
    copy:
      content: "{{ timezone }}"
      dest: /etc/timezone
      owner: root
      group: root
      mode: 0644
    notify: Update timezone
