---
  - name: Install dependencies
    apt:
      pkg: "{{ item }}"
      state: present
    with_items:
      - python-pycurl
      - python-software-properties

  - name: Add nodejs repository
    apt_repository:
      repo: ppa:chris-lea/node.js
      state: present
      update_cache: yes

  - name: Install nodejs
    apt:
      pkg: nodejs
      state: present

  - name: Install node packages
    npm:
      name: "{{ item }}"
      global: yes
    with_items: node_packages
