---
- name: Update nginx configuration
  template:
    src: etc/nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart nginx

- name: Disable the default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
   - Reload nginx
