---
- name: Update nginx configuration
  template:
    src: etc/nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart nginx

- name: Create necessary directories
  file:
    path: "{{ nginx_www_dir }}/{{ item.site.name }}"
    state: directory
  with_items: nginx_sites
  when: nginx_sites | length > 0

- name: Install nginx vhosts
  template:
    src: "etc/nginx/conf.d/{{ item.site.template }}.j2"
    dest: "/etc/nginx/conf.d/{{ item.site.name }}.conf"
  with_items: nginx_sites
  when: nginx_sites | length > 0
  notify: Reload nginx
