---
- name: Create necessary directories
  file:
    path: "{{ nginx_www_dir }}/{{ item.site.name }}"
    state: directory
  with_items: nginx_sites
  when: nginx_sites | length > 0

- name: Install nginx vhosts
  template:
    src: "etc/nginx/sites-available/{{ item.site.template }}.j2"
    dest: "/etc/nginx/sites-available/{{ item.site.name }}"
  with_items: nginx_sites
  when: nginx_sites | length > 0
  notify: Reload nginx