---
  - name: Create PostgreSQL databases
    postgresql_db:
      name: "{{ item.name }}"
      owner: "{{ postgresql_database_owner }}"
      encoding: "{{ postgresql_encoding }}"
      lc_collate: "{{ postgresql_locale }}"
      lc_ctype: "{{ postgresql_locale }}"
      template: "template0"
      state: present
      login_user: "{{ postgresql_admin_user }}"
    sudo_user: "{{ postgresql_admin_user }}"
    with_items: postgresql_databases
    when: postgresql_databases | length > 0
