---
- hosts: all
  user: vagrant
  sudo: True
  vars_files:
    - variables/sharing.yml
    - variables/dotfiles.yml
    - variables/nginx.yml
    - variables/postgresql.yml
    - variables/nodejs.yml
    - variables/ruby.yml
  roles:
    - ntp
    - dotfiles
    - nginx
    - postgresql
    - nodejs
    - ruby
    - netatalk
    - samba
