---
- hosts: all
  user: vagrant
  sudo: True
  vars_files:
    - variables/nginx.yml
    - variables/php.yml
    - variables/mysql.yml
    - variables/nodejs.yml
  roles:
    - common
    - nginx
    - php
    - mysql
    - nodejs
