---
- hosts: all
  user: vagrant
  sudo: True
  vars_files:
    - variables/sharing.yml
    - variables/dotfiles.yml
    - variables/nginx.yml
    - variables/nodejs.yml
    - variables/ruby.yml
  roles:
    - dotfiles
    - nginx
    - nodejs
    - ruby
    - netatalk
    - samba
